env:
  TERM: xterm-256color
window:
  padding:
    x: 0
    y: 0
bell:
  animation: EaseOutExpo
  duration: 0

cursor:
  style:
    shape: Beam
    blinking: always

mouse:
  hide_when_typing: true

background_opacity: 0.9
font:
  normal:
    family: FiraCode NF
  size: 14.0
  offset:
   x: 0
   y: 2
  glyph_offset:
   x: -1
   y: 0
colors:
  bright:
    black: '#4d4d4d'
    blue: '#6ca4f8'
    cyan: '#2b7489'
    green: '#56d364'
    magenta: '#db61a2'
    red: '#f78166'
    white: '#ffffff'
    yellow: '#e3b341'
  cursor:
    cursor: '#c9d1d9'
    text: '#ffffff'
  normal:
    black: '#000000'
    blue: '#6ca4f8'
    cyan: '#2b7489'
    green: '#56d364'
    magenta: '#db61a2'
    red: '#f78166'
    white: '#ffffff'
    yellow: '#e3b341'
  primary:
    background: '#101216'
    foreground: '#8b949e'
  selection:
    background: '#3b5070'
    text: '#ffffff'
